name: Cargo Version Update

on:
  pull_request:
    branches:
      - main
    paths:
      - src-tauri/Cargo.toml

jobs:
  update-cargo-lock:
    if: github.head_ref == 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Update Cargo.lock
        working-directory: src-tauri
        run: |
          cargo check
          cargo update

      - name: Commit Cargo.lock if changed
        run: |
          if git diff --exit-code src-tauri/Cargo.lock; then
            echo "No changes to Cargo.lock"
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add src-tauri/Cargo.lock
            git commit -m "chore: update Cargo.lock after version bump"
            git push
          fi
