name: Release

on:
  push:
    branches:
      - main
    # Only run if the commit is a changeset version commit
    # (by default, changeset version commit message starts with 'Version Packages')
    paths:
      - ".changeset/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "src/**"
      - "src-tauri/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Version packages with Changesets
        id: changesets
        run: pnpm changeset version

      - name: Sync Tauri version
        run: node sync-tauri-version.mjs

      - name: Build app (Tauri)
        run: pnpm tauri build

      - name: Upload installers
        uses: actions/upload-artifact@v4
        with:
          name: installers-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**/*.msi
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.rpm

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Version packages with Changesets
        id: changesets
        run: pnpm changeset version

      - name: Sync Tauri version
        run: node sync-tauri-version.mjs

      - name: Commit and push version sync
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src-tauri/Cargo.toml src-tauri/tauri.conf.json
          git commit -m "chore: sync tauri version" || echo "No changes to commit"
          git push

      - name: Download all installers
        uses: actions/download-artifact@v4
        with:
          path: installers

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.changesets.outputs.released_version || github.sha }}
          name: Release v${{ steps.changesets.outputs.released_version || github.sha }}
          body: |
            ${{ steps.changesets.outputs.released_notes || 'Automated release' }}
          files: installers/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
